import { WorkflowConfig } from './types.js';

export const config: WorkflowConfig = {
  discoveryIntervalMinutes: Number(process.env.DISCOVERY_INTERVAL_MINUTES ?? 30),
  replyCheckIntervalMinutes: Number(process.env.REPLY_CHECK_INTERVAL_MINUTES ?? 5),
  maxLeadsPerRun: Number(process.env.MAX_LEADS_PER_RUN ?? 5),
  sendChannels: ['email', 'sms', 'platform'],
  sourceAreas: [
    'Miami Beach, Florida',
    'Beverly Hills, California',
    'Malibu, California',
    'Monaco',
    'Aspen, Colorado'
  ],
  dryRun: process.env.DRY_RUN === 'true',
  testMode: process.env.TEST_MODE === 'true',
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? '',
  useLiveDiscovery: process.env.LIVE_DISCOVERY === 'true',
  useLiveMessaging: process.env.LIVE_MESSAGING === 'true',
  useLiveReplies: process.env.LIVE_REPLIES === 'true',
  useVideoGeneration: process.env.USE_VIDEO_GENERATION === 'true',
  leadSourceProvider: (process.env.LEAD_SOURCE_PROVIDER as 'google-places' | 'apify-airbnb' | 'mock') ?? 'apify-airbnb',
  leadSourceApiKey: process.env.GOOGLE_PLACES_API_KEY ?? '',
  apifyToken: process.env.APIFY_TOKEN ?? '',
  apifyActorId: process.env.APIFY_ACTOR_ID ?? '',
  apifyTaskId: process.env.APIFY_TASK_ID ?? '',
  apifyDatasetId: process.env.APIFY_DATASET_ID ?? '',
  apifyInput: process.env.APIFY_INPUT ?? '',
  apifyRunTimeoutMs: Number(process.env.APIFY_RUN_TIMEOUT_MS ?? 120000),
  sendgridApiKey: process.env.SENDGRID_API_KEY ?? '',
  sendgridSender: process.env.SENDGRID_SENDER ?? '',
  replySourceUrl: process.env.REPLY_SOURCE_URL ?? '',
  supabaseUrl: process.env.SUPABASE_URL ?? '',
  supabaseServiceKey: process.env.SUPABASE_SERVICE_KEY ?? '',
  landingPageUrl: process.env.LANDING_PAGE_URL ?? '',
  twilioAccountSid: process.env.TWILIO_ACCOUNT_SID ?? '',
  twilioAuthToken: process.env.TWILIO_AUTH_TOKEN ?? '',
  twilioSender: process.env.TWILIO_SENDER ?? '',
  airbnbApiToken: process.env.AIRBNB_API_TOKEN ?? '',
  airbnbBusinessProfileId: process.env.AIRBNB_BUSINESS_PROFILE_ID ?? '',
  mcpServerUrl: process.env.MCP_SERVER_URL ?? '',
  mcpApiKey: process.env.MCP_API_KEY ?? '',
  liveDashboardUrl: process.env.LIVE_DASHBOARD_URL ?? '',
  higgsfieldApiKey: process.env.HIGGSFIELD_API_KEY ?? '',
  higgsfieldProjectId: process.env.HIGGSFIELD_PROJECT_ID ?? '',
  higgsfieldModel: process.env.HIGGSFIELD_MODEL ?? 'higgsfield-mcp-video',
  higgsfieldCallbackUrl: process.env.HIGGSFIELD_CALLBACK_URL ?? ''
};
